import type { Metadata } from 'next';
import {Noto_Sans_KR } from 'next/font/google';
import './globals.css';
import {JSX} from "react";
import {NextFont, NextFontWithVariable} from "next/dist/compiled/@next/font";

const noto: NextFont = Noto_Sans_KR(
    {
      subsets: ['latin'],
      weight: ['300', '400', '500', '600', '700'],
      display: "swap",
    }
)

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}): JSX.Element {
  return (
    <html lang="ru">
      <body className={noto.className}>{children}</body>
    </html>
  )
}
